Mark out commit
dodopizza/MySqlConnector pull request #4
Opened 2022-11-28 14:30 UTC by yulianovikova

2022-11-29 09:59 UTC, aromanovdodo requested changes

2022-11-29 10:26 UTC, yulianovikova commented on src/MySqlConnector/MySqlTransaction.cs
> +	private async Task CommitAsync(IOBehavior ioBehavior, CancellationToken cancellationToken, string? commitMarkup = default)
Интерфейс оставлен. Это приватный метод. Публичный метод - `public Task CommitAsync(CancellationToken cancellationToken = default)` остался без изменений

2022-11-29 10:28 UTC, yulianovikova commented on src/MySqlConnector/MySqlTransaction.cs
> +	/// <param name="commitMarkup">Arbitrary markup attribute to be added to commit command</param>
Ок, могу переделать, заодно я поняла, что меня не очень устраивает схема версионирования, надо чуть-чуть допилить.

2022-11-29 10:30 UTC, aromanovdodo commented on src/MySqlConnector/MySqlTransaction.cs
> +	/// <param name="commitMarkup">Arbitrary markup attribute to be added to commit command</param>
Или `commitMark`, `commitTag`

2022-11-29 10:47 UTC, yulianovikova commented on src/MySqlConnector/MySqlTransaction.cs
> +	/// <param name="commitMarkup">Arbitrary markup attribute to be added to commit command</param>
Поменяла на commitComment

2022-11-29 11:01 UTC, aromanovdodo approved these changes

2022-12-17 18:31 UTC, bgrainger commented
I'm just curious: does adding a SQL comment allow this to be tracked in some kind of instrumentation or tracing system? What benefit does it provide?

2024-01-22 08:36 UTC, closed without merging